#!/usr/bin/env python

Import('env')

env.main_sources = []
env.add_source_files(env.main_sources, "*.cpp")

Export('env')

if (env['target'] == 'debug' or env['target'] == 'release_debug'):
    SConscript('tests/SCsub')

lib = env.Library("main", env.main_sources)

env.Prepend(LIBS=[lib])
