#!/usr/bin/env python

Import('env')

exc = []
if (env["disable_3d"] == "yes"):
    exc = [
        "animation_tree_player.cpp",
    ]

env.add_source_files(env.scene_sources, "*.cpp", exclude=exc)

Export('env')
