#!/usr/bin/env python

Import('env')

env.servers_sources = []

excludes = []
if (env["disable_3d"] == "yes"):
    excludes.append('physics_server.cpp')
    excludes.append('spatial_sound_server.cpp')

env.add_source_files(env.servers_sources, "*.cpp", exclude=excludes)

Export('env')

SConscript('visual/SCsub')
SConscript('audio/SCsub')

SConscript('physics_2d/SCsub')
if (env["disable_3d"] == "no"):
    SConscript('physics/SCsub')

SConscript('spatial_sound_2d/SCsub')
if (env["disable_3d"] == "no"):
    SConscript('spatial_sound/SCsub')

lib = env.Library("servers", env.servers_sources)

env.Prepend(LIBS=[lib])
