#!/usr/bin/env python

Import('env')

env.servers_sources = []

if (env["disable_3d"] == "yes"):
    env.servers_sources.append("physics_server.cpp")
    env.servers_sources.append("spatial_sound_server.cpp")

env.servers_sources.append("audio_server.cpp")
env.servers_sources.append("physics_2d_server.cpp")
env.servers_sources.append("register_server_types.cpp")
env.servers_sources.append("spatial_sound_2d_server.cpp")
env.servers_sources.append("visual_server.cpp")
#env.add_source_files(env.servers_sources, "*.cpp")

Export('env')

SConscript('visual/SCsub')
SConscript('audio/SCsub')

SConscript('physics_2d/SCsub')
if (env["disable_3d"] == "no"):
    SConscript('physics/SCsub')

SConscript('spatial_sound_2d/SCsub')
if (env["disable_3d"] == "no"):
    SConscript('spatial_sound/SCsub')

lib = env.Library("servers", env.servers_sources)

env.Prepend(LIBS=[lib])
