#!/usr/bin/env python

Import('env')

excludes = []
if (env['xml'] == 'no'):
    excludes.append('resource_format_xml.cpp')

env.add_source_files(env.core_sources, "*.cpp", exclude=excludes)

Export('env')
